Pakistan:
  - 'National'
  - 'National & Top Headlines'
  - 'Headlines & National'
  - 'Headlines & National & Top Headlines'
  - 'Pakistan'
  - 'Pakistan & Top Stories'
  - 'Pakistan & World'
  - 'Pakistan, World'
  - 'Pakistan, Islamabad'
  - 'Pakistan, Sindh'
  - 'Pakistan & Headlines'
  - 'Punjab'
  - 'Sindh'
  - 'Khyber Pakhtunkhwa'
  - 'K-P'
  - 'Balochistan'
  - 'Balochistan & Pakistan'
  - 'Balochistan & Pakistan & Top Stories'
  - 'Azad Jammu & Kashmir'
  - 'Islamabad'
  - 'Karachi'
  - 'Peshawar'
  - 'City'
  - 'Lahore'
  - 'Multan'
  - 'Governance & Headlines'
  - 'Top Stories & Pakistan'

World:
  - 'World'
  - 'Top Stories & World'
  - 'Headlines & World'
  - 'International'
  - 'Global'

Business:
  - 'Business'
  - 'Business & Top Stories'
  - 'Business & Finance'
  - 'Markets'
  - 'Economy'
  - 'Business & Economy'
  - 'Balochistan, Business'
  - 'Br Research'
  - 'Corporate'
  - 'Industry'
  - 'Money'
  - 'Trade'

Sports:
  - 'Sports'
  - 'Sport'
  - 'Cricket'
  - 'Score'

Technology:
  - 'Technology'
  - 'Sci-Tech'
  - 'Tech'
  - 'Gadgets'

Opinion:
  - 'Comment & Opinion'
  - 'Letters & Opinion'
  - 'Editorials & Opinion'
  - 'Editorial'
  - 'Editorials'
  - 'Op-Ed'
  - 'Opinion'
  - 'Prism'
  - 'Blogs'
  - 'Perspectives'
  - 'Commentary / Insight'
  - 'Analysis & National'
  - 'Analysis & Headlines'

Lifestyle:
  - 'Lifestyle'
  - 'Life & Style'
  - 'Reviews'
  - 'Infotainment'
  - 'Infotainment & Trending'
  - 'Film'
  - 'Gossip'
  - 'Music'
  - 'TV'
  - 'Spotlight'
  - 'Cartoons'
  - 'Art & Books'
  - 'Arts, Culture & Books'
  - 'Arts, Culture & Books & Trending'
  - 'Fashion'
  - 'Food'
  - 'Culture'

Other:
  - 'E-Papers & Pakistan Today'
  - 'Headlines'
  - 'Top Stories'
  - 'Top Stories & Headlines'
  - 'Uncategorized'
  - 'Source'
  - 'Categories'
  - 'Print'
  - 'Supplements'
  - ''
