Pakistan:
  - 'National'
  - 'National & Top Headlines'
  - 'Headlines & National'
  - 'Headlines & National & Top Headlines'
  - 'Pakistan'
  - 'Pakistan & Top Stories'
  - 'Pakistan & World'
  - 'Punjab'
  - 'Sindh'
  - 'Khyber Pakhtunkhwa'
  - 'K-P'
  - 'Balochistan'
  - 'Balochistan & Pakistan'
  - 'Balochistan & Pakistan & Top Stories'
  - 'Azad Jammu & Kashmir'
  - 'Islamabad'
  - 'Karachi'
  - 'Peshawar'
  - 'City'
  - 'Lahore'
  - 'Multan'
  - 'Governance & Headlines'

World:
  - 'World'
  - 'Top Stories & World'
  - 'Headlines & World'
  - 'Pakistan, World'

Business:
  - 'Business'
  - 'Business & Top Stories'
  - 'Markets'
  - 'Economy'
  - 'Balochistan, Business'

Sports:
  - 'Sports'
  - 'Sport'
  - 'Cricket'

Technology:
  - 'Technology'
  - 'Sci-Tech'

Opinion:
  - 'Comment & Opinion'
  - 'Letters & Opinion'
  - 'Editorials & Opinion'
  - 'Editorial'
  - 'Editorials'
  - 'Op-Ed'
  - 'Opinion'
  - 'Prism'
  - 'Blogs'
  - 'Perspectives'
  - 'Commentary / Insight'
  - 'Analysis & National'
  - 'Analysis & Headlines'

Lifestyle:
  - 'Lifestyle'
  - 'Life & Style'
  - 'Reviews'
  - 'Infotainment'
  - 'Infotainment & Trending'
  - 'Film'
  - 'Gossip'
  - 'Music'
  - 'TV'
  - 'Spotlight'
  - 'Cartoons'
  - 'Art & Books'
  - 'Arts, Culture & Books'
  - 'Arts, Culture & Books & Trending'

Other:
  - 'E-papers & Pakistan Today'
  - 'Headlines'
  - 'Top Stories'
  - 'Uncategorized'
  - 'Source'
  - 'Categories'
