Pakistan:
  - 'NATIONAL'
  - 'NATIONAL & Top Headlines'
  - 'HEADLINES & NATIONAL'
  - 'Pakistan'
  - 'Pakistan & Top Stories'
  - 'Punjab'
  - 'Sindh'
  - 'Khyber Pakhtunkhwa'
  - 'Balochistan'

World:
  - 'World'

Business:
  - 'Business'
  - 'Markets'
  - 'Economy'

Sports:
  - 'Sports'
  - 'Sport'
  - 'Cricket'
  - 'Football'
  - 'Tennis'

Technology:
  - 'Technology'
  - 'Sci-Tech'

Opinion:
  - 'Comment & Opinion'
  - 'Letters & Opinion'
  - 'Editorials & Opinion'
  - 'Editorial'
  - 'Editorials'
  - 'Op-Ed'
  - 'Prism'
  - 'Columns'

Lifestyle:
  - 'Lifestyle'
  - 'Reviews'
  - 'Infotainment'
  - 'Film'
  - 'Gossip'

Other:
  - 'E-papers & Pakistan Today'
  - 'source'
  - 'categories'
