extends: base.yaml

vectorizer:
  type: 'bow'
  ngram_range: [ 1, 2 ]
  max_features: 50000

classifier:
  type: 'svm'        # changed from 'logreg' to 'svm'
  logreg:
    C: 2.0
    class_weight: 'balanced'
  svm:
    C: 1.0           # tweak this if you want
  nb:
    alpha: 1.0
  rf:
    n_estimators: 200
    max_depth: 50

artifacts:
  classifier_filename: 'news_classifier_bow_svm.joblib'